[project]
name = "klassez"
version = "0.4a.12"
dependencies = [ 'numpy', 'scipy', 'lmfit', 'seaborn', 'nmrglue', 'matplotlib>=3.8', 'csaps', ]


[build-system]
requires = ['setuptools>=42']
build-backend = 'setuptools.build_meta'
